In [1]:
import numpy as np
import matplotlib
%matplotlib inline

In [2]:
x = np.array([[1, 2, 3], [4, 5, 6]], np.int32)
type(x)

numpy.ndarray

In [3]:
x.shape

(2, 3)

In [4]:
x.dtype

dtype('int32')

np.array的维度可以这样看
维度1：3 从外向里第一个数组的值
维度2: 2 从外向里第二个数组的值
维度3：4 里面第三个数组的值

In [11]:
x = np.array([[[10, 20, 30, 40],[41, 51, 61, 71]],
              [[11, 21, 31, 41],[45, 55, 65, 75]],
              [[12, 22, 32, 42],[46, 56, 66, 76]]], np.int32)
x.shape

(3, 2, 4)

In [12]:
x[1,1,1]

55

In [13]:
x

array([[[10, 20, 30, 40],
        [41, 51, 61, 71]],

       [[11, 21, 31, 41],
        [45, 55, 65, 75]],

       [[12, 22, 32, 42],
        [46, 56, 66, 76]]])

In [15]:
x = x.reshape(2, 4, 3)
x

array([[[10, 20, 30],
        [40, 41, 51],
        [61, 71, 11],
        [21, 31, 41]],

       [[45, 55, 65],
        [75, 12, 22],
        [32, 42, 46],
        [56, 66, 76]]])

In [23]:
x[0, :, :]

array([[10, 20, 30],
       [40, 41, 51],
       [61, 71, 11],
       [21, 31, 41]])

In [24]:
x[0, :, :].shape

(4, 3)

In [17]:
x[0]

array([[10, 20, 30],
       [40, 41, 51],
       [61, 71, 11],
       [21, 31, 41]])

In [20]:
x[:, 0, :]

array([[10, 20, 30],
       [45, 55, 65]])

In [22]:
x[:, 0, :].shape

(2, 3)

In [25]:
x[:, :, 0]

array([[10, 40, 61, 21],
       [45, 75, 32, 56]])

In [26]:
x[:, :, 0].shape

(2, 4)