In [1]:
import numpy as np
import matplotlib
%matplotlib inline

In [5]:
x = np.array([[[10, 20, 30, 40],[41, 51, 61, 71]],
              [[11, 21, 31, 41],[45, 55, 65, 75]],
              [[12, 22, 32, 42],[46, 56, 66, 76]]], np.int32)
x

array([[[10, 20, 30, 40],
        [41, 51, 61, 71]],

       [[11, 21, 31, 41],
        [45, 55, 65, 75]],

       [[12, 22, 32, 42],
        [46, 56, 66, 76]]])

In [3]:
x.shape

(3, 2, 4)

In [4]:
x[0, :, -1]

array([40, 71])

In [6]:
x[0, -1, :]  #[41,51,61,71]

array([41, 51, 61, 71])

In [7]:
x.ravel()

array([10, 20, 30, 40, 41, 51, 61, 71, 11, 21, 31, 41, 45, 55, 65, 75, 12,
       22, 32, 42, 46, 56, 66, 76])

In [14]:
x.flatten()

array([10, 20, 30, 40, 41, 51, 61, 71, 11, 21, 31, 41, 45, 55, 65, 75, 12,
       22, 32, 42, 46, 56, 66, 76])

In [18]:
print("before transpose, shape=", x.shape)
y = x.transpose()
print(x)
print("after transpose, shape=", y.shape)
print(y)

before transpose, shape= (3, 2, 4)
[[[10 20 30 40]
  [41 51 61 71]]

 [[11 21 31 41]
  [45 55 65 75]]

 [[12 22 32 42]
  [46 56 66 76]]]
after transpose, shape= (4, 2, 3)
[[[10 11 12]
  [41 45 46]]

 [[20 21 22]
  [51 55 56]]

 [[30 31 32]
  [61 65 66]]

 [[40 41 42]
  [71 75 76]]]


In [23]:
x1 = np.arange(0, 18).reshape(3, 3, 2)
x1

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]]])

In [27]:
x2 = np.array([[[ 10,  11],
        [ 12,  13],
        [ 14,  15]],

       [[ 16,  17],
        [ 18,  19],
        [110, 111]],

       [[112, 113],
        [114, 115],
        [116, 117]]])

np.hstack((x1, x2))

array([[[  0,   1],
        [  2,   3],
        [  4,   5],
        [ 10,  11],
        [ 12,  13],
        [ 14,  15]],

       [[  6,   7],
        [  8,   9],
        [ 10,  11],
        [ 16,  17],
        [ 18,  19],
        [110, 111]],

       [[ 12,  13],
        [ 14,  15],
        [ 16,  17],
        [112, 113],
        [114, 115],
        [116, 117]]])

In [28]:
np.hstack((x1, x2)).shape

(3, 6, 2)

In [30]:
np.vstack((x1, x2)).shape

(6, 3, 2)

In [31]:
np.concatenate((x1, x2), axis=-1)

array([[[  0,   1,  10,  11],
        [  2,   3,  12,  13],
        [  4,   5,  14,  15]],

       [[  6,   7,  16,  17],
        [  8,   9,  18,  19],
        [ 10,  11, 110, 111]],

       [[ 12,  13, 112, 113],
        [ 14,  15, 114, 115],
        [ 16,  17, 116, 117]]])

In [32]:
np.concatenate((x1, x2), axis=-1).shape

(3, 3, 4)

In [33]:
np.dstack((x1, x2)).shape

(3, 3, 4)

In [38]:
x1 = np.arange(0,4).reshape(2,2)
x1

array([[0, 1],
       [2, 3]])

In [40]:
x2 = np.arange(5,9).reshape(2,2)
x2

array([[5, 6],
       [7, 8]])

In [41]:
np.dstack((x1, x2))

array([[[0, 5],
        [1, 6]],

       [[2, 7],
        [3, 8]]])

In [42]:
np.dstack((x1, x2)).shape

(2, 2, 2)