In [1]:
import numpy as np
import matplotlib
%matplotlib inline

In [3]:
a1 = np.zeros((3,4,5), dtype=np.int32)
a1

array([[[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]]])

In [4]:
a2 = np.linspace(0, 2, 9) #等差数列
a2

array([ 0.  ,  0.25,  0.5 ,  0.75,  1.  ,  1.25,  1.5 ,  1.75,  2.  ])

In [6]:
a3 = np.full((2,2), 10)
a3

array([[10, 10],
       [10, 10]])

In [7]:
f = np.eye(2)
f

array([[ 1.,  0.],
       [ 0.,  1.]])

np.eye ：生成

In [11]:
f2 = np.eye(N=10, M=10, k=1)
f2

array([[ 0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])

In [18]:
r1 = np.random.randn(2,10)  #numpy.random.randn(d0, d1, …, dn)是从标准正态分布中返回一个或多个样本值。 
r1

array([[-0.81984719,  0.73655965, -1.28106118,  0.90838253, -0.11412435,
         1.22719876, -1.07913659,  0.86381409,  0.08245598, -0.87349157],
       [-0.40442111,  0.4332355 ,  0.81203031,  0.6710698 , -1.56709338,
         0.35306123,  0.04038259, -0.94799595, -0.04611911,  2.25806261]])

In [19]:
r1.mean(axis=0)

array([-0.61213415,  0.58489757, -0.23451543,  0.78972616, -0.84060887,
        0.79012999, -0.519377  , -0.04209093,  0.01816843,  0.69228552])