In [1]:
import numpy as np
import matplotlib
%matplotlib inline

In [3]:
a1 = np.mat([[1,  2,  3],
             [10, 20, 30]])

a2 = np.mat([[11, 21, 31],
             [11, 21, 31]])


matrix([[ 146,  146],
        [1460, 1460]])

In [4]:
a1*a2.T

matrix([[ 146,  146],
        [1460, 1460]])

In [6]:
a3 = np.multiply(a1, a2)
a3

matrix([[ 11,  42,  93],
        [110, 420, 930]])

In [7]:
a1.I

matrix([[ 0.00070721,  0.00707214],
        [ 0.00141443,  0.01414427],
        [ 0.00212164,  0.02121641]])

In [19]:
a1*a1.I

matrix([[ 0.00990099,  0.0990099 ],
        [ 0.0990099 ,  0.99009901]])

In [11]:
b1 = np.mat([[1,2],[-1,-3]])
b1

matrix([[ 1,  2],
        [-1, -3]])

In [12]:
b1.I

matrix([[ 3.,  2.],
        [-1., -1.]])

In [13]:
b1.I*b1

matrix([[ 1.,  0.],
        [ 0.,  1.]])

In [14]:
b1*b1.I

matrix([[ 1.,  0.],
        [ 0.,  1.]])

In [15]:
c1 = np.mat([[1,2],[-1,-3],[-1,-3]])
c1

matrix([[ 1,  2],
        [-1, -3],
        [-1, -3]])

In [16]:
c1.I

matrix([[ 3. ,  1. ,  1. ],
        [-1. , -0.5, -0.5]])

In [17]:
c1*c1.I

matrix([[  1.00000000e+00,  -3.33066907e-16,  -3.33066907e-16],
        [  0.00000000e+00,   5.00000000e-01,   5.00000000e-01],
        [  0.00000000e+00,   5.00000000e-01,   5.00000000e-01]])